<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4.3 Explorando las variables socio-ocupacionales en la EPH | Libro de Cocina para el Análisis de las Clases Sociales en Argentina</title>
  <meta name="description" content="Manual introductorio para el estudio de la estructura social en Argentina" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="4.3 Explorando las variables socio-ocupacionales en la EPH | Libro de Cocina para el Análisis de las Clases Sociales en Argentina" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Manual introductorio para el estudio de la estructura social en Argentina" />
  <meta name="github-repo" content="nsacco/libroESA" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4.3 Explorando las variables socio-ocupacionales en la EPH | Libro de Cocina para el Análisis de las Clases Sociales en Argentina" />
  
  <meta name="twitter:description" content="Manual introductorio para el estudio de la estructura social en Argentina" />
  

<meta name="author" content="Nicolás Sacco" />
<meta name="author" content="José Rodríguez de la Fuente" />
<meta name="author" content="Sofia Jaime" />


<meta name="date" content="2022-03-15" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="las-variables-socio-ocupacionales.html"/>

<script src="libs/header-attrs-2.13/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>
<link href="libs/vembedr-0.1.5/css/vembedr.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Manual para el Análisis de la Estructura Social Argentina Actual</a></li>

<li class="divider"></li>
<li><a href="index.html#prefacio">Prefacio<span></span></a></li>
<li><a href="agradecimientos.html#agradecimientos">Agradecimientos<span></span></a></li>
<li class="part"><span><b>I Introducción<span></span></b></span></li>
<li><a href="las-recetas.html#las-recetas">Las recetas<span></span></a></li>
<li class="part"><span><b>II Aspectos teóricos<span></span></b></span></li>
<li class="chapter" data-level="1" data-path="estructura1.html"><a href="estructura1.html"><i class="fa fa-check"></i><b>1</b> La estructura social en la Argentina actual<span></span></a>
<ul>
<li class="chapter" data-level="1.1" data-path="analisis1.html"><a href="analisis1.html"><i class="fa fa-check"></i><b>1.1</b> Del análisis de las clases sociales a la teoría de la estratificación social<span></span></a></li>
<li class="chapter" data-level="1.2" data-path="marx.html"><a href="marx.html"><i class="fa fa-check"></i><b>1.2</b> Marx, Weber y el funcionalismo<span></span></a></li>
<li class="chapter" data-level="1.3" data-path="esperanza.html"><a href="esperanza.html"><i class="fa fa-check"></i><b>1.3</b> La esperanza de vida de la teoría: debates contemporáneos<span></span></a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="esperanza.html"><a href="esperanza.html#la-grieta-de-los-ochenta"><i class="fa fa-check"></i><b>1.3.1</b> La grieta de los ochenta<span></span></a></li>
<li class="chapter" data-level="1.3.2" data-path="esperanza.html"><a href="esperanza.html#nuevos-debateshacia-una-operacionalización-más-refinada-de-los-conceptos"><i class="fa fa-check"></i><b>1.3.2</b> Nuevos debates…¿Hacia una operacionalización más refinada de los conceptos?<span></span></a></li>
<li class="chapter" data-level="1.3.3" data-path="esperanza.html"><a href="esperanza.html#la-muerte-de-la-clases"><i class="fa fa-check"></i><b>1.3.3</b> La muerte de la clases<span></span></a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="cuestion.html"><a href="cuestion.html"><i class="fa fa-check"></i><b>1.4</b> La cuestión en América Latina y en la Argentina<span></span></a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="cuestion.html"><a href="cuestion.html#nuevos-aires"><i class="fa fa-check"></i><b>1.4.1</b> Nuevos aires<span></span></a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>III Fuentes de datos<span></span></b></span></li>
<li class="chapter" data-level="2" data-path="fuentes.html"><a href="fuentes.html"><i class="fa fa-check"></i><b>2</b> Encuestas de hogares<span></span></a>
<ul>
<li class="chapter" data-level="2.1" data-path="eph1.html"><a href="eph1.html"><i class="fa fa-check"></i><b>2.1</b> La Encuesta Permanente de Hogares. Características principales<span></span></a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="eph1.html"><a href="eph1.html#características-de-la-eph-continua"><i class="fa fa-check"></i><b>2.1.1</b> Características de la EPH continua<span></span></a></li>
<li class="chapter" data-level="2.1.2" data-path="eph1.html"><a href="eph1.html#la-eph-como-fuente-de-análisis-de-la-estructura-de-clases"><i class="fa fa-check"></i><b>2.1.2</b> La EPH como fuente de análisis de la estructura de clases<span></span></a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="eph2.html"><a href="eph2.html"><i class="fa fa-check"></i><b>2.2</b> Comenzando a utilizar la EPH<span></span></a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="eph2.html"><a href="eph2.html#el-método-clásico"><i class="fa fa-check"></i><b>2.2.1</b> El “método clásico”<span></span></a></li>
<li class="chapter" data-level="2.2.2" data-path="eph2.html"><a href="eph2.html#el-paquete-eph"><i class="fa fa-check"></i><b>2.2.2</b> El paquete <code>eph</code><span></span></a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="eph3.html"><a href="eph3.html"><i class="fa fa-check"></i><b>2.3</b> Primeros pasos en el estudio de las clases sociales a través de la EPH<span></span></a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="eph3.html"><a href="eph3.html#uniendo-las-bases-de-individuos-y-hogares"><i class="fa fa-check"></i><b>2.3.1</b> Uniendo las bases de individuos y hogares<span></span></a></li>
<li class="chapter" data-level="2.3.2" data-path="eph3.html"><a href="eph3.html#población-bajo-análisis"><i class="fa fa-check"></i><b>2.3.2</b> Población bajo análisis<span></span></a></li>
<li class="chapter" data-level="2.3.3" data-path="eph3.html"><a href="eph3.html#ponderación-y-expansión-de-la-muestra"><i class="fa fa-check"></i><b>2.3.3</b> Ponderación y expansión de la muestra<span></span></a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="otras.html"><a href="otras.html"><i class="fa fa-check"></i><b>2.4</b> Otras encuestas de hogares para el estudio de la estructura de clases<span></span></a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="fuentes2.html"><a href="fuentes2.html"><i class="fa fa-check"></i><b>3</b> Los censos de población modernos<span></span></a>
<ul>
<li class="chapter" data-level="3.1" data-path="clases3.html"><a href="clases3.html"><i class="fa fa-check"></i><b>3.1</b> Clases sociales y censos de población<span></span></a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="clases3.html"><a href="clases3.html#antecedentes"><i class="fa fa-check"></i><b>3.1.1</b> Antecedentes<span></span></a></li>
<li class="chapter" data-level="3.1.2" data-path="clases3.html"><a href="clases3.html#practicidad"><i class="fa fa-check"></i><b>3.1.2</b> Practicidad<span></span></a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="censos.html"><a href="censos.html"><i class="fa fa-check"></i><b>3.2</b> Censos de población modernos. Características principales<span></span></a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="censos.html"><a href="censos.html#las-características-económicas-en-los-censos-de-población"><i class="fa fa-check"></i><b>3.2.1</b> Las características económicas en los censos de población<span></span></a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="censos2.html"><a href="censos2.html"><i class="fa fa-check"></i><b>3.3</b> Censos modernos: acceso diferencial<span></span></a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="censos2.html"><a href="censos2.html#modos-de-acceso"><i class="fa fa-check"></i><b>3.3.1</b> Modos de acceso<span></span></a></li>
<li class="chapter" data-level="3.3.2" data-path="censos2.html"><a href="censos2.html#es-lo-que-hay"><i class="fa fa-check"></i><b>3.3.2</b> Es lo que hay<span></span></a></li>
<li class="chapter" data-level="3.3.3" data-path="censos2.html"><a href="censos2.html#procesamiento-de-datos-en-líneau-1"><i class="fa fa-check"></i><b>3.3.3</b> Procesamiento de datos en línea<span></span></a></li>
<li class="chapter" data-level="3.3.4" data-path="censos2.html"><a href="censos2.html#descarga-directa-de-microdatos"><i class="fa fa-check"></i><b>3.3.4</b> Descarga directa de microdatos<span></span></a></li>
<li class="chapter" data-level="3.3.5" data-path="censos2.html"><a href="censos2.html#ipums-i"><i class="fa fa-check"></i><b>3.3.5</b> IPUMS-I<span></span></a></li>
<li class="chapter" data-level="3.3.6" data-path="censos2.html"><a href="censos2.html#solicitud-directa-al-indec"><i class="fa fa-check"></i><b>3.3.6</b> Solicitud directa al INDEC<span></span></a></li>
<li class="chapter" data-level="3.3.7" data-path="censos2.html"><a href="censos2.html#otras-opciones-no-oficiales"><i class="fa fa-check"></i><b>3.3.7</b> Otras opciones no oficiales<span></span></a></li>
<li class="chapter" data-level="3.3.8" data-path="censos2.html"><a href="censos2.html#disponibilidad-en-detalle-para-el-estudio-de-clases-sociales"><i class="fa fa-check"></i><b>3.3.8</b> Disponibilidad en detalle para el estudio de clases sociales<span></span></a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>IV Variables<span></span></b></span></li>
<li class="chapter" data-level="4" data-path="ocupacion.html"><a href="ocupacion.html"><i class="fa fa-check"></i><b>4</b> Las características económicas de la población<span></span></a>
<ul>
<li class="chapter" data-level="4.1" data-path="consideraciones.html"><a href="consideraciones.html"><i class="fa fa-check"></i><b>4.1</b> Consideraciones previas<span></span></a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="consideraciones.html"><a href="consideraciones.html#las-reglas-del-juego"><i class="fa fa-check"></i><b>4.1.1</b> Las reglas del juego<span></span></a></li>
<li class="chapter" data-level="4.1.2" data-path="consideraciones.html"><a href="consideraciones.html#la-estratificación-como-perspectiva-de-análisis"><i class="fa fa-check"></i><b>4.1.2</b> La estratificación como perspectiva de análisis<span></span></a></li>
<li class="chapter" data-level="4.1.3" data-path="consideraciones.html"><a href="consideraciones.html#indicadores-de-la-estratificación-social"><i class="fa fa-check"></i><b>4.1.3</b> Indicadores de la estratificación social<span></span></a></li>
<li class="chapter" data-level="4.1.4" data-path="consideraciones.html"><a href="consideraciones.html#la-fuerza-de-trabajo-y-las-características-económicas-de-la-población"><i class="fa fa-check"></i><b>4.1.4</b> La fuerza de trabajo y las características económicas de la población<span></span></a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="las-variables-socio-ocupacionales.html"><a href="las-variables-socio-ocupacionales.html"><i class="fa fa-check"></i><b>4.2</b> Las variables socio-ocupacionales<span></span></a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="las-variables-socio-ocupacionales.html"><a href="las-variables-socio-ocupacionales.html#condición-de-actividad"><i class="fa fa-check"></i><b>4.2.1</b> Condición de actividad<span></span></a></li>
<li class="chapter" data-level="4.2.2" data-path="las-variables-socio-ocupacionales.html"><a href="las-variables-socio-ocupacionales.html#ocupación"><i class="fa fa-check"></i><b>4.2.2</b> Ocupación<span></span></a></li>
<li class="chapter" data-level="4.2.3" data-path="las-variables-socio-ocupacionales.html"><a href="las-variables-socio-ocupacionales.html#rama-de-actividad"><i class="fa fa-check"></i><b>4.2.3</b> Rama de Actividad<span></span></a></li>
<li class="chapter" data-level="4.2.4" data-path="las-variables-socio-ocupacionales.html"><a href="las-variables-socio-ocupacionales.html#categoría-de-ocupación"><i class="fa fa-check"></i><b>4.2.4</b> Categoría de Ocupación<span></span></a></li>
<li class="chapter" data-level="4.2.5" data-path="las-variables-socio-ocupacionales.html"><a href="las-variables-socio-ocupacionales.html#sector-de-actividad"><i class="fa fa-check"></i><b>4.2.5</b> Sector de Actividad<span></span></a></li>
<li class="chapter" data-level="4.2.6" data-path="las-variables-socio-ocupacionales.html"><a href="las-variables-socio-ocupacionales.html#tamaño-del-establecimiento"><i class="fa fa-check"></i><b>4.2.6</b> Tamaño del Establecimiento<span></span></a></li>
<li class="chapter" data-level="4.2.7" data-path="las-variables-socio-ocupacionales.html"><a href="las-variables-socio-ocupacionales.html#supervisión"><i class="fa fa-check"></i><b>4.2.7</b> Supervisión<span></span></a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="eph4.html"><a href="eph4.html"><i class="fa fa-check"></i><b>4.3</b> Explorando las variables socio-ocupacionales en la EPH<span></span></a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="eph4.html"><a href="eph4.html#condición-de-actividad-1"><i class="fa fa-check"></i><b>4.3.1</b> Condición de actividad<span></span></a></li>
<li class="chapter" data-level="4.3.2" data-path="eph4.html"><a href="eph4.html#ocupación-1"><i class="fa fa-check"></i><b>4.3.2</b> Ocupación<span></span></a></li>
<li class="chapter" data-level="4.3.3" data-path="eph4.html"><a href="eph4.html#rama-de-actividad-1"><i class="fa fa-check"></i><b>4.3.3</b> Rama de actividad<span></span></a></li>
<li class="chapter" data-level="4.3.4" data-path="eph4.html"><a href="eph4.html#categoría-de-ocupación-1"><i class="fa fa-check"></i><b>4.3.4</b> Categoría de ocupación<span></span></a></li>
<li class="chapter" data-level="4.3.5" data-path="eph4.html"><a href="eph4.html#sector-de-actividad-1"><i class="fa fa-check"></i><b>4.3.5</b> Sector de actividad<span></span></a></li>
<li class="chapter" data-level="4.3.6" data-path="eph4.html"><a href="eph4.html#tamaño-del-establecimiento-1"><i class="fa fa-check"></i><b>4.3.6</b> Tamaño del establecimiento<span></span></a></li>
<li class="chapter" data-level="4.3.7" data-path="eph4.html"><a href="eph4.html#supervisión-1"><i class="fa fa-check"></i><b>4.3.7</b> Supervisión<span></span></a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Libro de Cocina para el Análisis de las Clases Sociales en Argentina</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="eph4" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Explorando las variables socio-ocupacionales en la EPH<a href="eph4.html#eph4" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Paquetes que utilizaremos en esta sección:</p>
<p>En este apartado aplicaremos lo aprendido en punto anterior y exploraremos las distintas variables revisadas a partir de la <strong>EPH</strong>. Lo que nos interesa es identificarlas, saber qué nombre tienen y como se presentan sus categorías. Al mismo tiempo, revisaremos algunas de las cuestiones aprendidas en el <a href="fuentes.html#fuentes">Capítulo 3</a>. Aprovecharemos a utilizar la base del segundo trimestre de la <strong>EPH</strong> de 2015, ya que en la misma, excepcionalmente, la ocupación fue codificada tanto a partir del <strong>CNO-01</strong> como de la <strong>CIUO-08</strong>. De esta forma, por un lado descargaremos a través del paquete <strong><code>eph</code></strong> y añadiremos la variable de ocupación descargando la información adicional desde la página de <strong>INDEC</strong>.</p>
<p>En primer lugar descargamos la base:</p>
<p>Como la codificación de la variable ocupación a partir de la <strong>CIUO</strong> se encuentra en un archivo aparte, debemos acceder al sitio de INDEC para descargarlo.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-48"></span>
<p class="caption">
Figure 4.3: Ejemplo clasificación de Actividades Profesionales, Científicas y Técnicas - CAES 1.0 <span class="citation">(<a href="eph4.html#ref-INDEC2011d" role="doc-biblioref">INDEC, 2011</a>)</span>
</p>
<img src="imagenes/indec_ciuo.png" alt="Ejemplo clasificación de Actividades Profesionales, Científicas y Técnicas - CAES 1.0 [@INDEC2011d]" width="80%" />
</div>
<p>Luego de descargado el archivo, descomprimiremos el <code>.rar</code> y utilizaremos el archivo <code>eph_ciuo_215.dbf</code>. A continuación abriremos dicho archivo y “pegaremos” la variable <strong>PP04D_CIUO</strong> en la base <strong>eph_ind_215</strong>. Utilizaremos las variables <strong>CODUSU</strong> (identificador de vivienda), <strong>NRO_HOGAR</strong> (identificador del hogar) y <strong>COMPONENTE</strong> (identificador de miembro del hogar) como ID para emparejar ambas bases.</p>
<p>Ahora podemos etiquetar la base utilizando el comando <code>organize_labels</code> del paquete <strong><code>eph</code></strong>:</p>
<p>¡Listo! La base está preparada para ser explorada.</p>
<div id="condición-de-actividad-1" class="section level3 hasAnchor" number="4.3.1">
<h3><span class="header-section-number">4.3.1</span> Condición de actividad<a href="eph4.html#condición-de-actividad-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>En la <strong>EPH</strong> la variable que mide la <strong>condición de actividad</strong> puede ser encontrada bajo el nombre “ESTADO”. Exploraremos las distintas categorías y frecuencias de casos que presenta para dicho trimestre.</p>
<pre><code>## 
## Entrevista individual no realizada (no respuesta al cuestionario individual) 
##                                                                           63 
##                                                                      Ocupado 
##                                                                        24398 
##                                                                   Desocupado 
##                                                                         1450 
##                                                                     Inactivo 
##                                                                        25138 
##                                                           Menor de 10 anios. 
##                                                                         8979</code></pre>
<p>Como puede observarse las categorías son <em>entrevista individual no realizada</em>, <em>ocupado</em>, <em>desocupado</em>, <em>inactivo</em> y <em>menor de 10 años</em>. En el caso de que pretendamos seleccionar únicamente a la población económicamente activa, deberemos filtrar las categorías 1 (ocupado) y 2 (desocupado). En este caso nos quedaríamos con 25848 registros.</p>
<pre><code>## [1] 25848</code></pre>
</div>
<div id="ocupación-1" class="section level3 hasAnchor" number="4.3.2">
<h3><span class="header-section-number">4.3.2</span> Ocupación<a href="eph4.html#ocupación-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Como presentaremos en la próxima unidad, la ocupación es la variable central en la construcción de esquemas de estratificación y clases sociales. En el caso de la EPH, los censos (posteriores a 1991) y las diversas encuestas que produce el <strong>INDEC</strong>, en las que se releva información ocupacional, suelen codificar dicha variable a través del <strong>CNO</strong>.</p>
<p>La <strong>EPH</strong> recaba la ocupación tanto para la población ocupada como desocupada, relevando para este último grupo el dato de la última ocupación realizada, en el caso que hubiera existido. Mientras que el primer dato se guarda en la variable <em>PP04D_COD</em>, la última ocupación de los desocupados puede encontrarse en la variable <em>PP11D_COD</em>. Con el comando <code>table</code> podemos visualizar todos los códigos existentes en la base y su frecuencia absoluta.</p>
<pre><code>## 
##       00001 01001 02001 03001 04001 05001 05002 06001 06002 07001 10112 10113 
## 35630    44     2    11    66    11   102   654   266     1     6    26    13 
## 10122 10131 10132 10133 10201 10202 10203 10311 10312 10313 10314 10323 10331 
##     1     2    12     8    12    53    60    11   136   118    31     2    29 
## 10332 10333 11113 11131 11132 11202 11203 11311 11312 11313 11323 11331 11332 
##    33  2127     1   108     2     2     3    10     4     6     1   112     4 
## 11333 20111 20112 20113 20131 20132 20133 20202 20203 20311 20312 20313 20314 
##    52     1     1     9    57     2     7    10    25     8     7   203     6 
## 20323 20331 20332 20333 30111 30112 30113 30131 30132 30133 30202 30203 30311 
##     1    94    67   354     2    74   930     3     1     9     1    71     8 
## 30312 30313 30314 30323 30331 30332 30333 31113 31312 31313 31314 32111 32113 
##   217   310  1018     1     4     2    23    58     2   148     3     1     1 
## 32123 32131 32133 32201 32202 32311 32312 32313 32314 32323 32333 33113 33133 
##     1     2     1     1     5     1     2     5   152     2    10   217     1 
## 33312 33313 33314 33333 34113 34123 34202 34203 34312 34313 34314 34323 34324 
##     2     8    20     3     3   241     6     9     5    15    30   939     4 
## 34331 34332 34333 35113 35123 35131 35201 35202 35203 35313 35314 35323 35333 
##     1     2     1     4    20     2     2     1     6    11    28   176     7 
## 36113 36203 36313 36314 36323 36333 40111 40112 40113 40131 40132 40201 40202 
##    13    16    57   104    59    70    77    57     2     5     2     4    17 
## 40203 40311 40312 40313 40314 40322 40323 40331 40332 40333 41111 41112 41113 
##     1   251   400    12    19    27     9    23    12     1     2   112     1 
## 41201 41202 41203 41311 41312 41313 41314 41323 41331 41332 41333 42131 42201 
##     5    10    14   115  1335    98     1     2    12     1     2     1     1 
## 42202 42203 42311 42313 42331 42332 42333 43111 43112 43131 43311 43331 43332 
##     1     4     4     7    39     5     6     1     2    22     1    40     4 
## 44111 44112 44113 44131 44132 44203 44312 44313 44331 45111 45112 45122 45123 
##     1     3     2     2     1     3    41    10     2     1     3     3     1 
## 45131 45132 45203 45311 45312 45322 45323 45331 45332 45662 46112 46202 46203 
##     5     3     1    11    34     8     2     7    30     1     3     3     1 
## 46311 46312 46313 46314 46331 46332 46333 47113 47203 47312 47313 47314 47323 
##    18    52    17     2     3     1     2     5     7     1   255    71     6 
## 48203 48311 48312 48313 48323 49202 49203 49311 49312 49313 49314 49323 49331 
##     5    27    65   309    14     1     1     3    14    53     4     5     1 
## 50111 50112 50113 50122 50131 50311 50312 50313 50322 51112 51202 51203 51312 
##    22     1     2     1     2    25     2     2     1    30     2     1    77 
## 51314 51331 52112 52113 52123 52203 52312 52313 52314 52323 52332 52333 53112 
##     3     1     3     2     4     3    13    20     2     5     4     3     2 
## 53113 53203 53312 53313 53314 53323 54112 54133 54311 54312 54313 54323 54332 
##   160    31     9   262   286     3     4     1     1    10    14     1     2 
## 54333 55203 55312 55314 56113 56123 56203 56313 56314 56323 57112 57113 57312 
##    12     3     1  1354    22     1     7    67   927    21     9   130     3 
## 57313 57314 58112 58113 58132 58203 58312 58313 58314 58323 58332 59313 60111 
##    30   437    11   128     1     1     8   108    13     2     2     1     2 
## 60113 60123 60131 60203 60311 60312 60313 60314 60323 60331 60332 60333 61113 
##     1     4     6     2     1     1    50     3    11     5     1     1     4 
## 61123 61203 61311 61313 61314 61323 61331 62313 62314 62323 63113 63313 63331 
##     2     1     1    10     2     1     1     5     1     4     1     2     2 
## 64113 64202 64313 64314 64323 64331 70131 70202 70203 70311 70312 70313 70322 
##     1     1     8     2     2     1     2     3    28     1     3    33     2 
## 70323 70331 70332 70333 71113 71201 71202 71203 71311 71312 71313 71323 71331 
##    27     8     2     1     1     2     1    10     1     3     9    12     6 
## 71332 71333 72112 72113 72131 72132 72201 72202 72203 72311 72312 72313 72314 
##     1     1    29   873    50     1     2     3    58     2    60  1068   576 
## 72323 72331 72332 72333 73113 74314 80111 80112 80113 80123 80131 80132 80202 
##    41    56    17     2     1     1     1    74   144   222     5     1     4 
## 80203 80311 80312 80313 80314 80322 80323 80331 80332 80333 81101 81121 81123 
##    64     4    24   516    63     4   688    21     2    10     1     1     2 
## 81131 81132 81201 81202 81323 81331 81332 81333 82111 82112 82113 82123 82131 
##    23     3    19     1     1    68     9     1     1    46   219    49     1 
## 82203 82312 82313 82314 82323 90112 90113 90203 90312 90313 90323 90331 90332 
##     2    23   192    32     7     4     5     6    14    76     6     1     2 
## 91311 92112 92113 92132 92202 92203 92312 92313 92331 92333 99999 
##     1    44     3     2     1     1    90    48     2     1    53</code></pre>
<p>Por otro lado, el paquete <strong><code>eph</code></strong> mediante la función <code>organize_CNO</code> nos agrega 4 columnas a la base en donde se clasifica cada componente del CNO: carácter, jerarquía, tecnología y calificación ocupacional. A continuación revisamos dicho comando y solicitaremos las frecuencias, por ejemplo, de la calificación.</p>
<pre><code>## 
## No calificados          Ns.Nc     Operativos  Profesionales       Técnicos 
##           5195             53          12879           2012           4259</code></pre>
<p>Por su parte en la variable <em>PP04D_CIUO</em> encontraremos a la ocupación codificada según el <strong>CIUO</strong>.</p>
<pre><code>## 
## 0110 0210 0310 1111 1112 1114 1120 1211 1212 1213 1219 1221 1222 1223 1311 1321 
##    4   10   34    4   45    7   34    5    4    1    6   45    1    1    7    5 
## 1322 1323 1324 1330 1341 1342 1343 1344 1345 1346 1349 1411 1412 1420 1431 1439 
##    1   14   12    5    1    8    2    1   76   15    6    5   24   68    1   14 
## 2111 2112 2113 2114 2120 2131 2132 2133 2141 2142 2143 2144 2145 2146 2149 2151 
##    1    3    1    6    1   38   20    5   17   33    4    4    6    2    3    8 
## 2152 2153 2161 2163 2164 2165 2166 2211 2212 2221 2240 2250 2261 2262 2263 2265 
##    5    2   80    9    1   10   21  121  110    3    2   19   58   30    6    3 
## 2266 2269 2310 2320 2330 2341 2342 2351 2352 2353 2354 2355 2356 2359 2411 2412 
##    5    9  164   39  426  487  177   20   50   24   27   34    4   83  189   14 
## 2413 2421 2422 2423 2424 2431 2432 2433 2434 2511 2512 2513 2514 2519 2521 2522 
##    2    5   19   51   11    8    3    7    1   33   20   22    9    2    4    8 
## 2523 2529 2611 2612 2619 2622 2631 2632 2633 2634 2635 2636 2641 2642 2643 2651 
##    9    2  242   10    1    3   11    2    1   86   26   12    3   54    5    5 
## 2652 2653 2654 2655 2656 2659 3111 3112 3113 3114 3115 3116 3117 3118 3119 3121 
##   21    2    6    8   17    3   13   29   12   25    6    3    7    8    4   23 
## 3122 3123 3131 3132 3133 3134 3135 3139 3141 3142 3143 3152 3153 3154 3155 3211 
##   71   92   21   14    3   14    1   18    6    2    1    4    2    3    3   40 
## 3212 3213 3214 3221 3222 3240 3251 3252 3253 3254 3255 3256 3257 3258 3259 3311 
##   37   10   16  257    2    2    6    4    3    6   52   11   54    3    1   15 
## 3312 3313 3314 3315 3321 3322 3323 3324 3331 3332 3333 3334 3339 3341 3342 3343 
##   34   77    8    6   47   72   14   66    9   17    5   40   47  109   32   91 
## 3344 3351 3352 3353 3354 3355 3359 3411 3412 3413 3421 3422 3423 3431 3432 3434 
##   27    1    9    3   10    9    9   36   55    5    7   34  104   23   11   17 
## 3435 3511 3512 3513 3514 3521 3522 4110 4120 4131 4132 4211 4212 4214 4221 4222 
##   33   23   13   19    9   30    8 1830  226    5   24   21   59   29   27   81 
## 4223 4224 4225 4226 4227 4229 4311 4312 4313 4321 4322 4323 4411 4412 4413 4415 
##   38   25   29   64    9    4  289    9   18  119   17   35   26   70    1    3 
## 4416 4419 5111 5112 5113 5120 5131 5132 5141 5142 5151 5152 5153 5161 5162 5163 
##    6   20    1    3   15  301  146   36  155   42    7    4   52    2    5    6 
## 5164 5165 5169 5211 5212 5221 5222 5223 5230 5241 5242 5243 5244 5245 5246 5249 
##   23    1    6   69   33 1122   93 1229  230    2    7  241   41   47   36    8 
## 5311 5312 5321 5322 5329 5411 5412 5413 5414 5419 6111 6112 6113 6114 6121 6122 
##  265  106   62  147   57   10  413   42  344   42    9    6   10   11   27    3 
## 6123 6130 6210 6222 6223 7111 7112 7113 7114 7115 7119 7121 7122 7123 7125 7126 
##    2    5    6    5    6    5 1240    3    4   58    3   10    8   11   11  163 
## 7127 7131 7132 7211 7212 7213 7214 7215 7221 7222 7223 7224 7231 7232 7233 7234 
##   39  177   31    2  126   74   17    2  108   23   34    3  318   14  141   14 
## 7311 7312 7313 7314 7315 7316 7317 7318 7319 7321 7322 7323 7411 7412 7413 7421 
##    3    3    4   10    5    9   22   63   25   19   52   13  185   73   44   28 
## 7422 7511 7512 7513 7514 7515 7516 7521 7522 7523 7531 7532 7533 7534 7535 7536 
##  111   54  115    7    1    9    1    4   74    3   73   10   63   27    1   40 
## 7542 7543 7544 7549 8111 8112 8113 8114 8121 8122 8131 8132 8141 8142 8143 8151 
##    2   34    9    9    3    3   37   12   44   14   17    2   28   35   13   21 
## 8152 8153 8154 8155 8156 8157 8159 8160 8172 8181 8182 8183 8189 8211 8212 8219 
##   12   73    5    2   18   23   24  102   30   19    2   53    5   28   88   18 
## 8311 8312 8321 8322 8331 8332 8341 8342 8343 8344 8350 9111 9112 9121 9122 9123 
##   10    9   49  758  179  242   18   25   24   58    6 1361  763   11   75    1 
## 9129 9211 9212 9213 9214 9215 9311 9312 9313 9321 9329 9331 9333 9334 9411 9412 
##    2   28   14    1  190    3    6   13  561   61   47    5  158  146   36  138 
## 9510 9520 9611 9612 9613 9621 9622 9623 9624 9629 9999 
##    8  113   45   41  108   32  123    7    1   21   41</code></pre>
<p>A través del paquete <strong><code>modest</code></strong> y el comando <code>mfv</code> (most frequent value) calcularemos la moda de dichas variables, es decir, la ocupación más repetida en el relevamiento.</p>
<pre><code>## [1] 4110
## 411 Levels: 0110 0210 0310 1111 1112 1114 1120 1211 1212 1213 1219 1221 ... 9999</code></pre>
<p>El código 4110 designa a los <strong>oficinistas generales</strong></p>
</div>
<div id="rama-de-actividad-1" class="section level3 hasAnchor" number="4.3.3">
<h3><span class="header-section-number">4.3.3</span> Rama de actividad<a href="eph4.html#rama-de-actividad-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Al igual que para el caso de la ocupación, la rama de actividad es computada tanto para la población ocupada como la desocupada. En los relevamientos previos a 2011 y posteriores a 2016, en el primer caso acudimos a la variable <em>PP04B_COD</em> mientras que en el segundo a la <em>PP11B_COD</em>. Para los relevamiento entre 2011 y 2015, dichas variables fueron nombradas sin el sufijo *_COD* y con el sufijo *_CAES*.</p>
<p>Echamos un vistazo a la distribución de la población ocupada según la rama de actividad.</p>
<pre><code>## 
##        0101  0102  0103  0104  0200  0300  0600  0700  0800  0900  1001  1002 
## 35630   101    43    35     1     6    15    48     4    26   100   116    43 
##  1003  1009  1100  1200  1300  1400  1501  1502  1600  1700  1800    19  1902 
##    37   383    53     5   120   156    13    57    41    31    67     3     8 
##    20  2001  2002  2009  2100  2201  2202  2301  2309  2400  2500  2601  2602 
##    24     6    30     5   101    33    62    14    63    26   406    18     7 
##  2603  2604  2701  2709  2800  2900  3001  3003  3009  3100  3200  3300  3501 
##    24    26    34    32    94    68     8     2    22   179   110   104   101 
##  3502  3600  3800  3900  4000  4501  4502  4503  4504    48  4801  4802  4803 
##    19    53   113     3  2575   100   398    74    48   126    21    35   777 
##  4804  4805  4806  4807  4808  4809  4810  4811    49  4901  4902  4903  4904 
##   427   168    80   651   827    41   416    28    15    36     1   582   302 
##  4909  5000  5100  5201  5202  5300  5500  5601  5602  5800  5900  6000  6100 
##    36    14    15    34   168   114   102   669    42    37    23    54   158 
##  6200  6300  6400  6500  6600  6800  6900  7000  7100  7200  7301  7302  7400 
##    95     7   219   179    12    55   371    60   136    36    40    11    91 
##  7500  7701  7702  7800  7900  8000  8101  8102  8200  8401  8402  8403  8501 
##    29    16     9    12    44   220   143   131   115  2094   990    76  1944 
##  8509  8600  8700  8800  9000  9100  9200  9301  9302  9401  9402  9409  9501 
##   229  1243    65    24    29    26   105   169    61    26    34   321    49 
##  9502  9503  9601  9602  9603  9609  9700     Z 
##     9   168    18   214    25    62  1780   113</code></pre>
<p>Del mismo modo que con la ocupación, el paquete <strong><code>eph</code></strong> mediante la función <code>organize_CAES</code> nos agrega 8 columnas a la base en donde se clasifican distintas cuestiones: versión de la CAES, código de sección y división, etiqueta de sección y división y clasificación de ramas de actividad agregadas. A continuación revisamos dicho comando y solicitaremos las frecuencias de las ramas agregadas.</p>
<pre><code>## 
##                               Actividades primarias 
##                                                 379 
##                             Industria manufacturera 
##                                                2631 
##                                        Construccion 
##                                                2575 
##                                            Comercio 
##                                                4217 
##                              Hoteles y restaurantes 
##                                                 813 
##         Transporte, almacenamiento y comunicaciones 
##                                                1691 
##  Servicios financieros, de alquiler y empresariales 
##                                                1929 
##  Administracion publica, defensa y seguridad social 
##                                                3084 
##                                           Ensenanza 
##                                                2173 
##                       Servicios sociales y de salud 
##                                                1332 
##                                  Servicio domestico 
##                                                1780 
## Otros servicios comunitarios, sociales y personales 
##                                                1316 
##                                         Otras ramas 
##                                                 169 
##                   Actividades no bien especificadas 
##                                                 120</code></pre>
</div>
<div id="categoría-de-ocupación-1" class="section level3 hasAnchor" number="4.3.4">
<h3><span class="header-section-number">4.3.4</span> Categoría de ocupación<a href="eph4.html#categoría-de-ocupación-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>La categoría de ocupación es una variable que también es de vital importancia en la construcción de clasificaciones. La misma puede encontrarse bajo el nombre de <em>CAT_OCUP</em>. A continuación exploramos sus categorías:</p>
<pre><code>## 
##                                    0                               Patron 
##                                34530                                  969 
##                        Cuenta propia                    Obrero o empleado 
##                                 4772                                19597 
## Trabajador familiar sin remuneracion 
##                                  160</code></pre>
</div>
<div id="sector-de-actividad-1" class="section level3 hasAnchor" number="4.3.5">
<h3><span class="header-section-number">4.3.5</span> Sector de actividad<a href="eph4.html#sector-de-actividad-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>En la <strong>EPH</strong> el sector de actividad puede encontrarse en la variable <em>PP04A</em>.</p>
<pre><code>## 
##               0      ...estatal      ...privada ...de otro tipo        Ns./Nr.. 
##           35630            5517           18492             373              16</code></pre>
</div>
<div id="tamaño-del-establecimiento-1" class="section level3 hasAnchor" number="4.3.6">
<h3><span class="header-section-number">4.3.6</span> Tamaño del establecimiento<a href="eph4.html#tamaño-del-establecimiento-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>La medición del tamaño del establecimiento se encuentra distribuida en dos variables: <em>PP04C</em> y <em>PP04C99</em>. La primera permite captar en forma detallada el tamaño del establecimiento donde trabaja la persona en diferentes rangos, mientras que la segunda permite recuperar, mediante una clasificación más acotada, aquel dato que en la primera variable figuraba como “Ns/Nc”. A continuación exploramos ambas variables en forma cruzada.</p>
<pre><code>##                        
##                             0 hasta 5 de 6 a 40 mas de 40 Ns./Nr..
##   0                     37370       0         0         0        0
##   1 persona              3565       0         0         0        0
##   2 personas             2123       0         0         0        0
##   3 personas             1241       0         0         0        0
##   4 personas              816       0         0         0        0
##   5 personas              752       0         0         0        0
##   6 a 10 personas        1876       0         0         0        0
##   11 a 25 personas       1783       0         0         0        0
##   26 a 40 personas       1567       0         0         0        0
##   de 41 a 100 personas   2035       0         0         0        0
##   de 101 a 200 personas  1386       0         0         0        0
##   de 201 a 500 personas  1204       0         0         0        0
##   mas de 500 personas    1304       0         0         0        0
##   Ns./Nr.                   0     125       610       919     1352</code></pre>
<p>Al igual que en el caso de la ocupación y la rama de actividad, para aquellas personas desocupadas que han trabajado alguna vez en el pasado, el tamaño del establecimiento puede ser identificado en las variables <em>PP11C</em> y <em>PP11C99</em>.</p>
</div>
<div id="supervisión-1" class="section level3 hasAnchor" number="4.3.7">
<h3><span class="header-section-number">4.3.7</span> Supervisión<a href="eph4.html#supervisión-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Si bien la supervisión no es una variable medida directamente en la <strong>EPH</strong>, podemos aproximarnos a dicha noción a través del <strong>CNO</strong>. En su tercer dígito mide la jerarquía ocupacional. Sin embargo, para extraer dicha información es necesario “partir” el código ocupacional, reteniendo el tercer dígito. A través de <strong><code>R</code></strong>, realizaremos la operación utilizando la función <code>str_sub</code> del paquete <strong><code>stringr</code></strong>, indicando que dígitos queremos retener. En este caso debemos señalar que queremos retener únicamente el tercer dígito (que empiece en el 3 y termine en el 3) y se lo asignaremos a una nueva variable llamada “cno_jerarquia”.</p>
<pre><code>## [1] 619</code></pre>
<p>Conociendo que el código 2 es el que hace referencia a la jefatura, si filtramos los resultados podemos decir que existen 619 casos que supervisan las tareas de otras personas.</p>

<div id="refs" class="references csl-bib-body hanging-indent" line-spacing="2">
<div id="ref-Adamovsky2009a" class="csl-entry">
Adamovsky, E. (2009a). <em>Argentina, ¿un país de clase media?</em> Buenos Aires: Canal 7 Argentina.
</div>
<div id="ref-Adamovsky2009b" class="csl-entry">
Adamovsky, E. (2009b). <em>Historia de la clase media argentina : Apogeo y decadencia de una ilusión, 1919-2003</em> (1a ed.). Buenos Aires: Planeta.
</div>
<div id="ref-Adamovsky2012" class="csl-entry">
Adamovsky, E. (2012). <em>Historia de las clases populares en la <span>Argentina</span> : Desde 1880 hasta 2003</em>. Buenos Aires: Editorial Sudamericana.
</div>
<div id="ref-Althusser1968" class="csl-entry">
Althusser, L., &amp; Balibar, E. (1968). <em>Lire "le <span>Capital</span>"</em>. Paris,: F. Maspero.
</div>
<div id="ref-Altimir1999" class="csl-entry">
Altimir, O., &amp; Beccaria, L. (1999). El mercado de trabajo bajo el nuevo régimen económico argentino. <em>Serie Reformas Económicas</em>, <em>68</em>.
</div>
<div id="ref-Bagu1959" class="csl-entry">
Bagú, S. (1959). <em>Estratificación y movilidad social en <span>Argentina</span></em>. Rio de Janeiro,.
</div>
<div id="ref-Barozet2007" class="csl-entry">
Barozet, E. (2007). <em>La variable ocupación en los estudios de estratificación social</em>. Documento de trabajo: Fondecyt 1060225.
</div>
<div id="ref-Bauman2000" class="csl-entry">
Bauman, Z. (2000). <em>Trabajo, consumismo y nuevos pobres</em>. Barcelona, España: Gedisa editorial.
</div>
<div id="ref-Beccaria2007" class="csl-entry">
Beccaria, L. (2007). Pobreza. In S. Torrado (Ed.), <em>Población y <span>Bienestar</span> en <span>Argentina</span> del <span>Primero</span> al <span>Segundo</span> <span>Centenario</span>. <span>Una</span> historia social del siglo <span>XX</span></em>. Buenos Aires: Edhasa.
</div>
<div id="ref-Bell2006" class="csl-entry">
Bell, D. (2006). <em>El advenimiento de la sociedad post-industrial : Un intento de prognosis social</em>. Madrid: Alianza.
</div>
<div id="ref-Benza2012" class="csl-entry">
Benza, G. (2012). <em>Estructura de clases y movilidad intergeneracional en <span>Buenos</span> <span>Aires</span>: ¿El fin de una sociedad de <span>“amplias clases medias”</span>?</em> (PhD thesis). tesis de doctorado, México, El Colegio de México, Centro de Estudios Sociológicos.
</div>
<div id="ref-Benza2016" class="csl-entry">
Benza, G. (2016). La estructura de clases argentina durante la década 2003-2013. In G. Kessler (Ed.), <em>La sociedad argentina hoy: Radiografía de una nueva estructura social</em> (pp. 111–139). Buenos Aires: Siglo Veintiuno Editores.
</div>
<div id="ref-Blau.Duncan1967" class="csl-entry">
Blau, P. M., &amp; Duncan, O. D. (1967). <em>The <span>American</span> occupational structure</em>. New York: John Wiley &amp; Sons.
</div>
<div id="ref-Bourdieu2012" class="csl-entry">
Bourdieu, P. (2012). <em>La distinción. <span>Criterio</span> y bases sociales del gusto</em>. Buenos Aires: Taurus.
</div>
<div id="ref-Budlender2003" class="csl-entry">
Budlender, D. (2003). <em>Improving occupational classifications as tools for describing labour markets: <span>A</span> summary of recent national experiences</em>.
</div>
<div id="ref-Burris1995" class="csl-entry">
Burris, V. (1995). La síntesis neomarxista de <span>Marx</span> y <span>Weber</span> sobre las clases. In J. Carabaña &amp; A. de Francisco (Eds.), <em>Teorías contemporáneas de las clases sociales</em> (3. ed., pp. 128–156). Madrid: Editorial Pablo Iglesias.
</div>
<div id="ref-Carabana1997" class="csl-entry">
Carabaña, J. (1997). Esquemas y estructuras. <em>Revista Crítica de Ciências Sociais</em>, (49), 67–91.
</div>
<div id="ref-ChavezMolina.etal2020" class="csl-entry">
Chávez Molina, E., Bernasconi, F., &amp; Rodríguez de la Fuente, J. J. (2020). <em>Propuesta de correspondencias entre <span>CNO</span> y <span>CIUO</span>. <span>Sintaxis</span> para <span>SPSS</span>, <span>STATA</span> y <span>R</span>.</em> Buenos Aires: IIGG. Retrieved from <a href="http://iigg.sociales.uba.ar/2020/09/30/his-6-propuesta-de-correspondencias-entre-cno-y-ciuo-sintaxis-para-spss-stata-y-r/?fbclid=IwAR3RvLDs7H8wYHDqUooZMEI74HIDS6MXT3YbEjstG44yt0DB9tFj0VwlT9A">http://iigg.sociales.uba.ar/2020/09/30/his-6-propuesta-de-correspondencias-entre-cno-y-ciuo-sintaxis-para-spss-stata-y-r/?fbclid=IwAR3RvLDs7H8wYHDqUooZMEI74HIDS6MXT3YbEjstG44yt0DB9tFj0VwlT9A</a>
</div>
<div id="ref-ChavezMolina2009" class="csl-entry">
Chávez Molina, E., &amp; Molina Derteano, P. (2009). <em>La movilidad socio-ocupacional en la mira. <span>Un</span> estudio de caso exploratorio para debatir viejas y nuevas cuestiones</em>. Facultad de Ciencias Económicas de la Universidad Nacional de Buenos Aires.
</div>
<div id="ref-ChavezMolina2014" class="csl-entry">
Chávez Molina, E., &amp; Sacco, N. (2014). <em>Reconfiguraciones en la estructura social: Dos décadas de cambios en los procesos distributivos. <span>Análisis</span> del <span>GBA</span> según en el clasificador de clases ocupacionales basado en la heterogeneidad estructural 1992-2013</em> [{CD}-{ROM}]. Jujuy, Argentina.
</div>
<div id="ref-ChavezMolina2015" class="csl-entry">
Chávez Molina, E., &amp; Sacco, N. (2015). Reconfiguraciones en la estructura social: Dos décadas de cambios en los procesos distributivos. <span>Análisis</span> del <span>GBA</span> según en el clasificador de clases ocupacionales basado en la heterogeneidad estructural 1992-2013. In J. Lindenboim &amp; A. Salvia (Eds.), <em>Hora de balance: Proceso de acumulación, mercado de trabajo y bienestar. <span>Argentina</span>, 2002-2014</em> (pp. 287–312). Ciudad Autónoma de Buenos Aires: Eudeba.
</div>
<div id="ref-Clark1991" class="csl-entry">
Clark, T. N., &amp; Lipset, S. M. (1991). Are social classes dying? <em>International Sociology</em>, <em>6</em>(4), 397–410.
</div>
<div id="ref-Crompton2008" class="csl-entry">
Crompton, R. (2008). <em>Class and stratification</em> (3rd ed.). Cambridge: Polity.
</div>
<div id="ref-Dahrendorf1979" class="csl-entry">
Dahrendorf, R. (1979). <em>Las clases sociales y su conflicto en la sociedad industrial</em> (M. Troyano de los Ríos, Trans.). Madrid: Rialp.
</div>
<div id="ref-Dalle2016" class="csl-entry">
Dalle, P. (2016). <em>Movilidad social desde las clases populares: Un estudio sociológico en el área <span>Metropolitana</span> de <span>Buenos</span> <span>Aires</span> 1960-2013</em>. Buenos Aires: IIGG-CLACSO.
</div>
<div id="ref-Dalle.etal2018" class="csl-entry">
Dalle, P., Jorrat, J. R., &amp; Riveiro, M. (2018). Movilidad social intergeneracional. In A. Salvia &amp; J. I. Piovani (Eds.), <em>La <span>Argentina</span> en el siglo <span>XXI</span>. <span>Cómo</span> somos, vivimos y convivimos en una sociedad desigual. <span>Encuesta</span> <span>Nacional</span> sobre la <span>Estructura</span> <span>Social</span>.</em> Buenos Aires: Siglo Veintiuno Editores.
</div>
<div id="ref-Dalle.Stiberman2017" class="csl-entry">
Dalle, P., &amp; Stiberman, L. (2017). Clases populares en <span>Argentina</span>: Cambios recientes en su composición ocupacional (1998-2015). <em>Encrucijadas - Revista Crítica de Ciencias Sociales</em>, <em>14</em>(0), 1405. Retrieved from <a href="http://www.encrucijadas.org/index.php/ojs/article/view/300">http://www.encrucijadas.org/index.php/ojs/article/view/300</a>
</div>
<div id="ref-Desrosieres2000" class="csl-entry">
Desrosières, A., &amp; Thévenot, L. (2000). <em>Les catégories socioprofessionnelles</em>. Paris: Ed. la Découverte.
</div>
<div id="ref-Elizalde1987" class="csl-entry">
Elizalde, M. L. (1987). Un desafío para el censo de 1990: ¿Qué hacer con las ocupaciones? In INDEC (Ed.), <em>Los censos del 90. <span>Características</span> económicas de la población</em>. Buenos Aires: INDEC.
</div>
<div id="ref-Elizalde1993" class="csl-entry">
Elizalde, M. L. (1993). La información estadística de ocupaciones: <span>Una</span> línea de investigación en la construcción de datos primarios. <em>Estudios Del Trabajo</em>, <em>5</em>, 121–153.
</div>
<div id="ref-Erikson1992" class="csl-entry">
Erikson, R., &amp; Goldthorpe, J. H. (1992). <em>The constant flux : A study of class mobility in industrial societies</em>. Oxford England New York: Clarendon Press ; Oxford University Press.
</div>
<div id="ref-FeitoAlonso1995" class="csl-entry">
Feito Alonso, R. (1995). <em>Estructura social contemporánea : Las clases sociales en los países industrializados</em> (1. ed.). Madrid: Siglo XXI de España Editores.
</div>
<div id="ref-Fernandes1998" class="csl-entry">
Fernandes, F., &amp; Zenteno, R. B. (1998). <em>Las clases sociales en <span>América</span> <span>Latina</span>: Problemas de conceptualización : Seminario de <span>Merida</span>, <span>Yuc</span>., 13 al 18 de diciembre de 1971</em>. Siglo XXI Ediciones.
</div>
<div id="ref-Filgueira2001" class="csl-entry">
Filgueira, C. (2001). <em>La actualidad de viejas temáticas: Sobre los estudios de clase, estratificación y movilidad social en <span>América</span> <span>Latina</span></em>. CEPAL.
</div>
<div id="ref-Filgueira1981" class="csl-entry">
Filgueira, C. H., &amp; Geneletti, C. (1981). <em>Estratificación y movilidad ocupacional en <span>América</span> <span>Latina</span></em>. Santiago de Chile: Naciones Unidas.
</div>
<div id="ref-Franco2010" class="csl-entry">
Franco, R., Hopenhayn, M., &amp; León, A. (2010). <em>Las clases medias en <span>América</span> <span>Latina</span>. <span>Retrospectiva</span> y nuevas tendencias</em>. Siglo veintiuno editores Naciones Unidas.
</div>
<div id="ref-Franco2010a" class="csl-entry">
Franco, R., &amp; León, A. (2010). Clases medias latinoamericanas: Ayer y hoy. <em>Estudios Avanzados</em>, <em>13</em>, 59–77.
</div>
<div id="ref-Franco2007" class="csl-entry">
Franco, R., León, A., &amp; Atria, R. (2007). <em>Estratificación y movilidad social en <span>América</span> <span>Latina</span>. <span>Transformaciones</span> estructurales de un cuarto de siglo</em>. Santiago, Chile: CEPAL.
</div>
<div id="ref-Fujihara2020" class="csl-entry">
Fujihara, S. (2020). Socio-<span>Economic</span> <span>Standing</span> and <span>Social</span> <span>Status</span> in <span>Contemporary</span> <span>Japan</span>: <span>Scale</span> <span>Constructions</span> and <span>Their</span> <span>Applications</span>. <em>European Sociological Review</em>, <em>36</em>(4), 548–561.
</div>
<div id="ref-Furbanck2005" class="csl-entry">
Furbanck, P. N. A. (2005). <em>Un placer inconfesable o la idea de clase social</em>. Buenos Aires, Barcelona, México: Paidós.
</div>
<div id="ref-Ganzeboom1992" class="csl-entry">
Ganzeboom, H. B. G., De Graaf, P. M., Treiman, D. J., &amp; De Leeuw, J. (1992). A <span>Standard</span> <span>International</span> <span>Socio</span>-<span>Economic</span> <span>Index</span> of <span>Occupational</span> <span>Status</span>. <em>Social Science Research</em>, <em>21</em>(1), 1–56.
</div>
<div id="ref-Ganzeboom1996" class="csl-entry">
Ganzeboom, H. B. G., &amp; Treiman, D. J. (1996). Internationally <span>Comparable</span> <span>Measures</span> of <span>Occupational</span> <span>Status</span> for the 1988 <span>International</span> <span>Standard</span> <span>Classification</span> of <span>Occupations</span>. <em>Social Science Research</em>, <em>25</em>(3), 201–239.
</div>
<div id="ref-Garguin2009" class="csl-entry">
Garguin, E. (2009). "<span>Los</span> argentinos descendemos de los barcos”. <span>Articulación</span> racial de la identidad de clase media en <span>Argentina</span> (1920-1960). In S. E. Visacovsky &amp; E. Garguin (Eds.), <em>Moralidades, economías e identidades de clase media</em>.
</div>
<div id="ref-Germani1944" class="csl-entry">
Germani, G. (1944). Sociografía de la clase media en <span>Buenos</span> <span>Aires</span>: <span>Las</span> características culturales de la clase media de <span>Buenos</span> <span>Aires</span> estudiadas a través de la forma de empleo de las horas libres. <em>Boletín Del Instituto de Sociología, Facultad de Filosofía y Letras, Universidad de Buenos Aires</em>.
</div>
<div id="ref-Germani1963" class="csl-entry">
Germani, G. (1963). La movilidad social en la <span>Argentina</span>. In <em>Movilidad social en la sociedad industrial</em>. Buenos Aires: EUDEBA.
</div>
<div id="ref-Germani1981" class="csl-entry">
Germani, G. (1981). La clase media en la ciudad de <span>Buenos</span> <span>Aires</span>: <span>Estudio</span> preliminar. <em>Desarrollo Económico, Buenos Aires</em>, <em>21</em>(81).
</div>
<div id="ref-Germani1987" class="csl-entry">
Germani, G. (1987). <em>Estructura social de la <span>Argentina</span>; análisis estadístico</em>. Ediciones Solar.
</div>
<div id="ref-Giddens1998" class="csl-entry">
Giddens, A. (1998). <em>La constitución de la sociedad: Bases para la teoría de la estructuración</em>. Amorrortu Editores España SL.
</div>
<div id="ref-Giusti2007" class="csl-entry">
Giusti, A. (2007). Censos modernos: 1960, 1970, 1980, 1991, 2001. In S. Torrado (Ed.), <em>Población y <span>Bienestar</span> en <span>Argentina</span> del <span>Primero</span> al <span>Segundo</span> <span>Centenario</span>. <span>Una</span> historia social del siglo <span>XX</span></em> (pp. 215–244). Buenos Aires: EDHASA.
</div>
<div id="ref-Goldthorpe1995" class="csl-entry">
Goldthorpe, J. (1995). Sobre la clase de servicio, su formación y su futuro. In J. Carabaña, A. de Francisco, &amp; (Compiladores) (Eds.), <em>Teorías contemporáneas de las clases sociales</em>. Madrid: Pablo Iglesias.
</div>
<div id="ref-GomezRojas.Riveiro2014" class="csl-entry">
Gómez Rojas, G., &amp; Riveiro, M. (2014). Hacia una mirada de género en los estudios de movilidad social: Interrogantes teórico-metodológicos. <em>Boletín Científico Sapiens Research</em>, <em>4</em>(1), 26–31. Retrieved from <a href="https://www.srg.com.co/bcsr/index.php/bcsr/article/view/74">https://www.srg.com.co/bcsr/index.php/bcsr/article/view/74</a>
</div>
<div id="ref-Gouldner2000" class="csl-entry">
Gouldner, A. W. (2000). <em>La crisis de la sociología occidental</em>. Buenos Aires: Amorrortu.
</div>
<div id="ref-Graciarena1971" class="csl-entry">
Graciarena, J. (1971). Clases medias y movimiento estudiantil. <span>El</span> <span>Reformismo</span> <span>Argentino</span>: 1918-1966. <em>Revista Mexicana de Sociologia</em>, <em>33</em>(1), 61–100.
</div>
<div id="ref-Hoffmann1999" class="csl-entry">
Hoffmann, E. (1999). <em>International <span>Statistical</span> <span>Comparisons</span> of <span>Occupational</span> and <span>Social</span> <span>Structures</span>: <span>Problems</span>, <span>Possibilities</span> and the <span>Role</span> of <span>ISCO</span>-88</em>. ILO, Bureau of Statistics.
</div>
<div id="ref-Hout1993" class="csl-entry">
Hout, M., Brooks, C., &amp; Manza, J. (1993). The persistence of classes in post-industrial societies. <em>International Sociology International Sociology</em>, <em>8</em>(3), 259–277.
</div>
<div id="ref-INDEC1990" class="csl-entry">
INDEC. (1990). <em>El <span>Código</span> de <span>Ocupaciones</span> para el <span>Censo</span> de <span>Población</span>: El estado actual de su desarrollo, sus posibilidades operativas y analíticas</em>. Programa de Clasificación Nacional de Ocupaciones: INDEC.
</div>
<div id="ref-INDEC1991" class="csl-entry">
INDEC. (1991). <em>Categorías, divisiones, grupos y clases de la <span>Revisión</span> 3 de la <span>Clasificación</span> <span>Internacional</span> <span>Industrial</span> <span>Uniforme</span> (<span>CIIU</span>)</em>. Buenos Aires.
</div>
<div id="ref-INDEC1998" class="csl-entry">
INDEC. (1998). <em>Aquí se cuenta. <span>Revista</span> informativa del <span>Censo</span> 2000. <span>N</span>°1</em>. Buenos Aires.
</div>
<div id="ref-INDEC2000" class="csl-entry">
INDEC. (2000). <em>Censo <span>Experimental</span>. <span>Noviembre</span> de 1999. <span>Pergamino</span>. <span>Análisis</span> de la cobertura censal</em>. Buenos Aires.
</div>
<div id="ref-INDEC2000a" class="csl-entry">
INDEC. (2000). <em>Utilización de clasificadores de ocupación en las bases de datos de la encuesta permamente de hogares</em>.
</div>
<div id="ref-INDEC2003" class="csl-entry">
INDEC. (2003). <em>La nueva <span>Encuesta</span> <span>Permanente</span> de <span>Hogares</span> de <span>Argentina</span>: 2003</em>. Retrieved from <a href="https://www.indec.gob.ar/ftp/cuadros/sociedad/metodologia_eph_continua.pdf">https://www.indec.gob.ar/ftp/cuadros/sociedad/metodologia_eph_continua.pdf</a>
</div>
<div id="ref-INDEC2005" class="csl-entry">
INDEC. (2005). <em>Clasificador <span>Nacional</span> de <span>Ocupaciones</span> 2001</em> (INDEC, Ed.). Buenos Aires: INDEC.
</div>
<div id="ref-INDEC2011d" class="csl-entry">
INDEC. (2011). <em>Clasificación de <span>Actividades</span> <span>Económicas</span> para <span>Encuestas</span> <span>Sociodemográficas</span> del <span>MERCOSUR</span>. <span>CAES</span>-<span>MERCOSUR</span> 1.0 <span>Versión</span> <span>Argentina</span></em>. Buenos Aires.
</div>
<div id="ref-INDEC2018" class="csl-entry">
INDEC. (2018). <em>Clasificador <span>Nacional</span> de <span>Ocupaciones</span> (<span>CNO</span>). <span>Definiciones</span> conceptuales.</em> Retrieved from <a href="https://www.indec.gob.ar/ftp/cuadros/menusuperior/clasificadores/definiciones_conceptuales_cno.pdf">https://www.indec.gob.ar/ftp/cuadros/menusuperior/clasificadores/definiciones_conceptuales_cno.pdf</a>
</div>
<div id="ref-INDEC2018a" class="csl-entry">
INDEC. (2018). <em><span>CNO</span>. <span>Clasificador</span> <span>Nacional</span> de <span>Ocupaciones</span>. <span>Versión</span> 2017</em>. Retrieved from <a href="https://www.indec.gob.ar/ftp/cuadros/menusuperior/clasificadores/CNO_2017.pdf">https://www.indec.gob.ar/ftp/cuadros/menusuperior/clasificadores/CNO_2017.pdf</a>
</div>
<div id="ref-INDEC2018b" class="csl-entry">
INDEC. (2018). <em><span>CNO</span>. <span>Correspondencias</span> entre el <span>CNO</span>-17 y la <span>CIUO</span>-08.</em> Retrieved from <a href="https://www.indec.gob.ar/ftp/cuadros/menusuperior/clasificadores/correspondencias_cno2017_ciuo2008.pdf">https://www.indec.gob.ar/ftp/cuadros/menusuperior/clasificadores/correspondencias_cno2017_ciuo2008.pdf</a>
</div>
<div id="ref-INDEC2020" class="csl-entry">
INDEC. (2020). <em>Encuesta <span>Permanente</span> de <span>Hogares</span>. <span>Diseño</span> de registro y estructura para las bases preliminares <span>Hogar</span> y <span>Personas</span>.</em> INDEC. Retrieved from <a href="https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_registro_1t20.pdf">https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_registro_1t20.pdf</a>
</div>
<div id="ref-Inglehart1990" class="csl-entry">
Inglehart, R. (1990). <em>Culture shift in advanced industrial society</em>. PRINCETON University Press.
</div>
<div id="ref-InigoCarrera1999" class="csl-entry">
Iñigo Carrera, N., Podestá, J., &amp; Cotarelo, M. C. (1999). Las estructuras económico sociales concretas que constituyen la formación económica de la <span>Argentina</span>. <em>Programa de Investigación Sobre El Movimiento de La Sociedad Argentina (PIMSA)</em>, <em>Documento de Trabajo Nº 18</em>.
</div>
<div id="ref-Ipola1976" class="csl-entry">
Ipola, E. de, &amp; Torrado, S. (1976). <em>Teoría y método para el estudio de la estructura de clases sociales (<span>Con</span> un análisis concreto: <span>Chile</span>, 1970)</em>. Santiago: Flacso-Proelce.
</div>
<div id="ref-Kerbo2003" class="csl-entry">
Kerbo, H. R. (2003). <em>Estratificación y desigualdad. <span>El</span> conflicto de clases en perspectiva histórica, comparada y global</em> (7th ed.). Madrid, España: McGraw-Hill/ Interamericana de España, S.A.U.
</div>
<div id="ref-Kessler2007" class="csl-entry">
Kessler, G., &amp; Espinoza, V. (2007). Movilidad social y trayectorias ocupacionales en <span>Buenos</span> <span>Aires</span>. <span>Continuidades</span>, rupturas y paradojas. In R. Franco, A. León, &amp; R. Atria (Eds.), <em>Estratificación y movilidad social en <span>América</span> <span>Latina</span>: Transformaciones estructurales de un cuarto de siglo</em> (1. ed., pp. 614 p.). Santiago, Chile: LOM Ediciones, CEPAL, GTZ.
</div>
<div id="ref-kozlowski2020" class="csl-entry">
Kozlowski, D., Tiscornia, P., Weksler, G., Rosati, G., &amp; Shokida, N. (2020). <em>Eph: <span>Argentina</span>’s permanent household survey data and manipulation utilities</em> [Manual]. <a href="https://doi.org/10.5281/zenodo.3462677">https://doi.org/10.5281/zenodo.3462677</a>
</div>
<div id="ref-Kritz1987" class="csl-entry">
Kritz, E. H. (1987). Posibilidades de medición de la subutilización de la fuerza de trabajo a través de los censos de población. In INDEC (Ed.), <em>Los <span>Censos</span> del 90: Características económicas de la población</em>. Buenos Aires: INDEC.
</div>
<div id="ref-Laclau1987" class="csl-entry">
Laclau, E., &amp; Mouffe, C. (1987). <em>Hegemonía y estrategia socialista : Hacia una radicalización de la democracia</em>. Madrid [etc.]: Siglo XXI.
</div>
<div id="ref-Levine2006" class="csl-entry">
Levine, R. F. (2006). <em>Social class and stratification: Classic statements and theoretical debates</em>. Rowman &amp; Littlefield Publishers.
</div>
<div id="ref-Lindenboim2007" class="csl-entry">
Lindenboim, J. (2007). La fuerza de trabajo en el siglo <span>XX</span>. <span>Viejas</span> y nuevas discusiones. In S. Torrado (Ed.), <em>Población y <span>Bienestar</span> en <span>Argentina</span> del <span>Primero</span> al <span>Segundo</span> <span>Centenario</span>. <span>Una</span> historia social del siglo <span>XX</span></em>. Buenos Aires: Edhasa.
</div>
<div id="ref-LoVuolo2004c" class="csl-entry">
Lo Vuolo, R., Barbeito, A., Pautassi, L., &amp; Rodríguez, C. (2004). <em>La pobreza ... De la política contra la pobreza.</em> Buenos Aires: Ceipp.
</div>
<div id="ref-Lockwood1962" class="csl-entry">
Lockwood, D. (1962). <em>El trabajador de la clase media un estudio sobre la conciencia de clase</em>. Madrid: Aguilar.
</div>
<div id="ref-Lopez2005a" class="csl-entry">
López, A., &amp; Romeo, M. (2005). <em>La declinación de la clase media argentina : Transformaciones en la estructura social, 1974-2004</em> (1. ed.). Buenos Aires: Aurelia Rivera.
</div>
<div id="ref-Losada2009" class="csl-entry">
Losada, L. (2009). <em>Historia de las elites en la <span>Argentina</span>: Desde la <span>Conquista</span> hasta el surgimiento del peronismo</em>. Buenos Aires: Sudamericana.
</div>
<div id="ref-Martinez2005" class="csl-entry">
Martínez, R. (2005). <em>Estructura social y estratificación</em> (2° ed.; C. editor de la Universidad Pablo Olavide Sevilla, Ed.). Buenos Aires-Madrid: Miño y Dávila.
</div>
<div id="ref-MedinaEchavarria1964" class="csl-entry">
Medina Echavarría, J. (1964). <em>Consideraciones sociológicas sobre el desarrollo económico de <span>América</span> <span>Latina</span></em>. Buenos Aires: Solar: Hachette.
</div>
<div id="ref-Minoldo.Born2019" class="csl-entry">
Minoldo, S., &amp; Born, D. (2019). <em>Claroscuros: 9 años de datos bajo sospecha (<span>EPH</span> en <span>Argentina</span> entre 2007 y 2015)</em>. Retrieved from <a href="https://issuu.com/cieseditora/docs/claroscuros_minoldo-born">https://issuu.com/cieseditora/docs/claroscuros_minoldo-born</a>
</div>
<div id="ref-Minujin1987" class="csl-entry">
Minujín, A. (1987). Acerca de los censos del 90. In INDEC (Ed.), <em>Los <span>Censos</span> del 90 : Características económicas de la población</em>. Buenos Aires: INDEC.
</div>
<div id="ref-Minujin1992" class="csl-entry">
Minujín, A. (1992). <em>Cuesto abajo: Los nuevos pobres: Efectos de la crisis en la sociedad argentina</em> (1a ed.). Buenos Aires: UNICEF : LOSADA.
</div>
<div id="ref-Minujin2004" class="csl-entry">
Minujín, A., &amp; Anguita, E. (2004). <em>La clase media: Seducida y abandonada</em> (1. ed.). Buenos Aires: Edhasa.
</div>
<div id="ref-Minujin1995" class="csl-entry">
Minujín, A., &amp; Kessler, G. (1995). <em>La nueva pobreza en la <span>Argentina</span></em>. Buenos Aires, Argentina: Editorial Planeta.
</div>
<div id="ref-Monza1986" class="csl-entry">
Monza, A., &amp; Planificación, S. de. (1986). <em>El terciario argentino y el ajuste del mercado de trabajo urbano (1947-1980)</em>.
</div>
<div id="ref-Murmis1992" class="csl-entry">
Murmis, M., &amp; Feldman, S. (1992). Posibilidades y fracasos de las clase medias, según <span>Germani</span>. In J. R. Jorrat &amp; R. Sautu (Eds.), <em>Después de <span>Germani</span>: <span>Exploraciones</span> sobre estructura social de la <span>Argentina</span></em> (pp. 278 p.). Buenos Aires: Paidos.
</div>
<div id="ref-Nisbet1959" class="csl-entry">
Nisbet, R. A. (1959). The decline and fall of social class. <em>Pacific Sociological Review</em>, <em>2</em>(1), 11–17.
</div>
<div id="ref-OIT" class="csl-entry">
OIT. (n.d.). <em>Clasificación <span>Internacional</span> <span>Uniforme</span> de <span>Ocupaciones</span></em>.
</div>
<div id="ref-OIT2008" class="csl-entry">
OIT. (2008). <em>Clasificación <span>Internacional</span> <span>Uniforme</span> de <span>Ocupaciones</span> (<span>CIUO</span>-08) – <span>Marco</span> conceptual</em>. OIT.
</div>
<div id="ref-OIT2008a" class="csl-entry">
OIT. (2008). <em>Resolución sobre la actualización de la <span>Clasificación</span> <span>Internacional</span> <span>Uniforme</span> de <span>Ocupaciones</span></em>. OIT.
</div>
<div id="ref-ONU1997" class="csl-entry">
ONU. (1997). <em>Manual de censos de población y habitación. <span>Parte</span> 4, actividad económica</em>. Nueva York.
</div>
<div id="ref-ONU2009a" class="csl-entry">
ONU, &amp; CEPAL. (2009). <em>Estudio <span>Económico</span> de <span>América</span> <span>Latina</span> y el <span>Caribe</span> 2009-2010: Impacto distributivo de las políticas públicas</em>. Santiago de Chile: CEPAL.
</div>
<div id="ref-ONUOIT2010" class="csl-entry">
ONU-OIT. (2010). <em>Medición de la población económicamente activa en los censos de población: <span>Manual</span></em>. Nueva York: Naciones Unidas/ Oficina Internacional del Trabajo.
</div>
<div id="ref-Orsatti1985" class="csl-entry">
Orsatti, Á. (1985). El empleo precario en <span>Buenos</span> <span>Aires</span>, 1974-1983. In <em>El empleo precario en <span>Argentina</span></em>. Buenos Aires: CIAT-Ministerio de Trabajo y Seguridad Social.
</div>
<div id="ref-Ossowski1972" class="csl-entry">
Ossowski, S. (1972). <em>Estructura de clases y conciencia social</em>. Barcelona: Península.
</div>
<div id="ref-Palomino.Dalle2012" class="csl-entry">
Palomino, H., &amp; Dalle, P. (2012). El impacto de los cambios ocupacionales en la estructura social de la <span>Argentina</span>: 2003-2011. <em>Revista de Trabajo</em>, <em>10</em>(8), 205–223. Retrieved from <a href="http://www.trabajo.gob.ar/downloads/estadisticas/2012n10_revistaDeTrabajo.pdf">http://www.trabajo.gob.ar/downloads/estadisticas/2012n10_revistaDeTrabajo.pdf</a>
</div>
<div id="ref-Parkin1968" class="csl-entry">
Parkin, F. (1968). <em>Middle class radicalism; the social bases of the <span>British</span> <span>Campaign</span> for <span>Nuclear</span> <span>Disarmament</span></em>. New York,: F. A. Praeger.
</div>
<div id="ref-Pla2016" class="csl-entry">
Pla, J. (2016). <em>Condiciones objetivas y esperanzas subjetivas. <span>Movilidad</span> social y marcos de (in) certidumbre. <span>Un</span> abordaje multidimensional de las trayectorias de clase. <span>Argentina</span> durante la primera década del siglo <span>XXI</span></em>. Buenos Aires: Editorial Autores de Argentina.
</div>
<div id="ref-Pla.etal2018" class="csl-entry">
Pla, J., Rodríguez de la Fuente, J., &amp; Sacco, N. (2018). Clases sociales y condiciones de vida en el <span>Gran</span> <span>Buenos</span> <span>Aires</span> (2003-2013). <em>Revista Colombiana de Sociología</em>, <em>41</em>(2), 189–231. <a href="https://doi.org/10.15446/rcs.v41n2.64743">https://doi.org/10.15446/rcs.v41n2.64743</a>
</div>
<div id="ref-Portes2003" class="csl-entry">
Portes, A. (2003). <em>Las estructuras de clase en <span>América</span> <span>Latina</span>: Composición y cambios durante la época neoliberal</em>. CEPAL, Divisiâon de Desarrollo Social.
</div>
<div id="ref-Poulantzas2005" class="csl-entry">
Poulantzas, N. (2005). <em>Les clases sociales en el capitalismo actual</em>. Buenos Aires, Argentina: Siglo veintiuno editores.
</div>
<div id="ref-Povina1950" class="csl-entry">
Poviña, A. (1950). Concepto de la clase media y proyección argentina. In T. R. Crevenna (Ed.), <em>Materiales para el estudio de la clase media en la <span>América</span> <span>Latina</span></em>. Washington: Unión Panamericana.
</div>
<div id="ref-Przeworski1977" class="csl-entry">
Przeworski, A. (1977). Proletariat into a <span>Class</span>: <span>The</span> <span>Process</span> of <span>Class</span> <span>Formation</span> from <span>Karl</span> <span>Kautsky</span>’s <span>The</span> <span>Class</span> <span>Struggle</span> to <span>Recent</span> <span>Controversies</span>. <em>Politics &amp; Society Politics &amp; Society</em>, <em>7</em>(4), 343–401.
</div>
<div id="ref-RodriguezdelaFuente2020" class="csl-entry">
Rodríguez de la Fuente, J. J. (2020). <em>Del origen de clase a las condiciones de vida actuales. <span>Movilidad</span> social y bienestar material en la <span>Ciudad</span> de <span>Buenos</span> <span>Aires</span> (2004-2015)</em>. Buenos Aires: Teseo Press. Retrieved from <a href="https://www.teseopress.com/origendeclase/">https://www.teseopress.com/origendeclase/</a>
</div>
<div id="ref-Rose2007" class="csl-entry">
Rose, D., &amp; Harrison, E. (2007). The <span>European</span> socio-economic classification: A new social class schema for comparative european research. <em>European Societies</em>, <em>9</em>(3), 459–490. <a href="https://doi.org/10.1080/14616690701336518">https://doi.org/10.1080/14616690701336518</a>
</div>
<div id="ref-Sacco2015" class="csl-entry">
Sacco, N. (2015). <em>¿<span>Cierran</span> los números con la gente adentro? <span>Principales</span> resultados de una evaluación general del censo argentino de 2010</em>. Ciudad de Salta, Provincia de Salta, Argentina.
</div>
<div id="ref-Sacco2019" class="csl-entry">
Sacco, N. (2019). Estructura social de la <span>Argentina</span>, 1976-2011. <em>Trabajo y Sociedad</em>, (32), 25–51. Retrieved from <a href="https://dialnet.unirioja.es/servlet/articulo?codigo=6856110">https://dialnet.unirioja.es/servlet/articulo?codigo=6856110</a>
</div>
<div id="ref-Sacco2016b" class="csl-entry">
Sacco, N., &amp; Riveiro, M. (2016). La clasificación de ocupaciones en el <span>Sistema</span> <span>Estadístico</span> <span>Nacional</span>. <em>Estudios Del Trabajo</em>, <em>51</em>.
</div>
<div id="ref-Sautu2011" class="csl-entry">
Sautu, R. (2011). <em>El análisis de las clases sociales: Teorías y metodologías</em> (Sociología, Ed.). Buenos Aires: Luxemburg.
</div>
<div id="ref-Sno.Ganzeboom2017" class="csl-entry">
Sno, T. E., &amp; Ganzeboom, H. B. (2017). <em><span>THE</span> <span>OCCUPATIONAL</span> <span>STRATIFICATION</span> <span>OF</span> <span>SURINAME</span>: <span>HOTDOG</span> <span>OR</span> <span>POM</span>? <span>A</span> <span>COMPARISON</span> <span>OF</span> <span>AN</span> <span>INTERNATIONAL</span> <span>AND</span> <span>A</span> <span>COUNTRY</span>-<span>SPECIFIC</span> <span>SEI</span>-<span>SCALE1</span></em>.
</div>
<div id="ref-Solis.etal2019" class="csl-entry">
Solís, P., Chávez Molina, E., &amp; Cobos, D. (2019). Class <span>Structure</span>, <span>Labor</span> <span>Market</span> <span>Heterogeneity</span>, and <span>Living</span> <span>Conditions</span> in <span>Latin</span> <span>America</span>. <em>Latin American Research Review</em>, <em>54</em>(4). Retrieved from <a href="https://larrlasa.org/articles/10.25222/larr.442/">https://larrlasa.org/articles/10.25222/larr.442/</a>
</div>
<div id="ref-Tedesco1973" class="csl-entry">
Tedesco, J. C. (1973). <em>Clases sociales y educación en la <span>Argentina</span></em>. Rosario: Ediciones Centro de Estudios.
</div>
<div id="ref-Thompson1968" class="csl-entry">
Thompson, E. P. (1968). <em>The making of the <span>English</span> working class</em> ([New). Harmondsworth: Penguin.
</div>
<div id="ref-Tokman1987" class="csl-entry">
Tokman, V. E. (1987). El sector informal: Quince años después. <em>El Trimestre Económico</em>, <em>54</em>(215 (3), 513–536. Retrieved from <a href="http://www.jstor.org/stable/23397333">http://www.jstor.org/stable/23397333</a>
</div>
<div id="ref-Torrado1992" class="csl-entry">
Torrado, S. (1992). <em>Estructura social de la <span>Argentina</span>, 1945-1983</em> (2a ed.). Buenos Aires, República Argentina: Ediciones de la Flor.
</div>
<div id="ref-Torrado1993" class="csl-entry">
Torrado, S. (1993a). El <span>“<span>Clasificador</span> <span>Nacional</span> de <span>Ocupaciones</span>”</span> (<span>CNO</span>-91). <span>Crítica</span> de la razón autoritaria. <em>Estudios Del Trabajo</em>, <em>6</em>, 113–136.
</div>
<div id="ref-Torrado1993a" class="csl-entry">
Torrado, S. (1993b). El nuevo ‘<span>Clasificador</span> <span>Nacional</span> de <span>Ocupaciones</span> del <span>INDEC</span>: Una fractura irreparable en el sistema estadístico nacional. <em>Estudios Del Trabajo</em>, <em>5</em>, 85–120.
</div>
<div id="ref-Torrado1998" class="csl-entry">
Torrado, S. (1998). Clases sociales, familia y comportamiento demográfico: Orientaciones metodológicas. In S. Torrado (Ed.), <em>Familia y diferenciación social: Cuestiones de método</em> (1a. ed., pp. 33–61). Buenos Aires: EUDEBA.
</div>
<div id="ref-Torrado2003a" class="csl-entry">
Torrado, S. (2003). <em>Historia de la familia en la <span>Argentina</span> moderna (1870-2000)</em>. Buenos Aires, Argentina: Ediciones de la Flor.
</div>
<div id="ref-Torrado2007" class="csl-entry">
Torrado, S. (2007). Estrategias de desarrollo, estructura social y movilidad. In S. Torrado (Ed.), <em>Población y bienestar en la <span>Argentina</span> del primero al segundo centenario. <span>Una</span> historia social del siglo <span>XX</span></em>: <em>Vol.</em> <em>I</em>. Buenos Aires: Edhasa.
</div>
<div id="ref-Torrado1985" class="csl-entry">
Torrado, S., &amp; Orsatti, Á. (1985). Hacia un clasificador de la condición socioeconómica utilizable en censos y encuestas de hogares. In INDEC (Ed.), <em>Los censos de población del 80. <span>Taller</span> de análisis y evaluación</em>: <em>Vol.</em> <em>Estudios 2</em>. Buenos Aires: INDEC-CELADE-Agencia Canadiense para el desarrollo internacional.
</div>
<div id="ref-Torrado1988" class="csl-entry">
Torrado, S., &amp; Rofman, R. (1988). <em>Clases sociales, familia y comportamientos sociodemográficos : <span>Argentina</span> 1970</em>. Buenos Aires: Centro de Estudios Urbanos y Regionales.
</div>
<div id="ref-Treiman1977" class="csl-entry">
Treiman, D. J. (1977). <em>Occupational prestige in comparative perspective</em>. New York: Academic Press.
</div>
<div id="ref-Visacovsky2009" class="csl-entry">
Visacovsky, S. E., &amp; Garguin, E. (2009). <em>Moralidades, economías e identidades de clase media. <span>Estudios</span> históricos y etnográficos</em>. Buenos Aires: Antropofagia.
</div>
<div id="ref-Weber2002" class="csl-entry">
Weber, M. (2002). <em>Economía y sociedad: Esbozo de sociología comprensiva</em> (J. Winckelmann &amp; J. M. Echevarría, Eds.). México: Fondo de Cultura Económica.
</div>
<div id="ref-Wortman2003" class="csl-entry">
Wortman, A., &amp; Arizaga, C. (2003). <em>Pensar las clases medias : Consumos culturales y estilos de vida urbanos en la <span>Argentina</span> de los noventa</em> (1. ed.). Ciudad Autónoma de Buenos Aires, Argentina: La Crujía Ediciones.
</div>
<div id="ref-Wright1995a" class="csl-entry">
Wright, E. O. (1995). Reflexionando, una vez más, sobre el concepto de estructura de clases. In J. Carabaña &amp; A. de Francisco (Eds.), <em>Teorías contemporáneas de las clases sociales</em> (3. ed., pp. 263 p.). Madrid: Editorial Pablo Iglesias.
</div>
<div id="ref-Wright1997" class="csl-entry">
Wright, E. O. (1997). <em>Class counts : Comparative studies in class analysis</em>. Cambridge ; New York Paris: Cambridge University Press ; Maison des sciences de l’homme.
</div>
<div id="ref-Wright2005" class="csl-entry">
Wright, E. O. (2005). <em>Approaches to class analysis</em>. Cambridge, UK ; New York: Cambridge University Press.
</div>
<div id="ref-Zimmermann2000" class="csl-entry">
Zimmermann, E. A. (2000). La sociedad entre 1870 y 1914. In <em>Nueva <span>Historia</span> de la <span>Nación</span> <span>Argentina</span></em>: <em>Vol.</em> <em>Tomo 4</em>. Buenos Aires: Planeta.
</div>
</div>
</div>
</div>
<!-- </div> -->
<div class="footnotes footnotes-end-of-document">
<hr />
<ol>
<li id="fn1"><p>Nota: parte de esta sección fue tomada de del sitio web de OLAC.<a href="esperanza.html#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>Nota: parte de esta sección fue tomada de del sitio web de OLAC.<a href="censos2.html#fnref2" class="footnote-back">↩︎</a></p></li>
<li id="fn3"><p>Este texto está tomado parcialmente de <span class="citation">Sacco &amp; Riveiro (<a href="eph4.html#ref-Sacco2016b" role="doc-biblioref">2016</a>)</span><a href="las-variables-socio-ocupacionales.html#fnref3" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="las-variables-socio-ocupacionales.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["clases-arg.pdf", "clases-arg.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

</body>

</html>
